using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.Model.Concepts;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Acts
{
    /// <summary>
    /// Represents a specific consideration or arrangement made for the encounter
    /// </summary>
    [Table("pat_enc_arg_tbl")]
    public class DbPatientEncounterArrangement : DbActVersionedAssociation
    {
        /// <summary>
        /// Gets or sets the primary key of the object
        /// </summary>
        [Column("arg_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the type of arrangement
        /// </summary>
        [Column("typ_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid ArrangementTypeKey { get; set; }

        /// <summary>
        /// Gets or sets the start time of the arrangement
        /// </summary>
        [Column("start_utc")]
        public DateTimeOffset? StartTime { get; set; }

        /// <summary>
        /// Gets or sets the stop time of the arrangement
        /// </summary>
        [Column("stop_utc")]
        public DateTimeOffset? StopTime { get; set; }
    }
}
