using SanteDB.Core.Data;
using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.ADO.Data.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Data.ADO.Data.Index
{
    /// <summary>
    /// Filter index definition table
    /// </summary>
    [Table("pf_systbl")]
    public class DbPreparedFilterDefinition : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the id of the prepared filter index
        /// </summary>
        [PrimaryKey, NotNull, Column("pf_id"), AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the name of the filter
        /// </summary>
        [Column("name")]
        public String Name { get; set; }

        /// <summary>
        /// Sequence of this PF
        /// </summary>
        [Column("seq_id"), AutoGenerated]
        public int SequenceId { get; set; }

        /// <summary>
        /// Gets or sets the status
        /// </summary>
        [Column("sts_cs_id"), NotNull]
        public PreparedFilterIndexState Status { get; set; }

        /// <summary>
        /// The filter expression
        /// </summary>
        [Column("expr"), NotNull]
        public String FilterExpression { get; set; }

        /// <summary>
        /// Gets or sets additional indexing providers
        /// </summary>
        [Column("idxr")]
        public String Indexer { get; set; }

        /// <summary>
        /// Gets or sets the target type
        /// </summary>
        [Column("trg_typ")]
        public String TargetType { get; set; }

        /// <summary>
        /// The last time the index was rebuilt
        /// </summary>
        [Column("lst_rdx")]
        public DateTimeOffset LastReindex { get; set; }

        /// <summary>
        /// The store table name
        /// </summary>
        [Column("pf_tbl_id"), NotNull]
        public String StoreName { get; set; }
    }
}
