using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.DataType
{
    /// <summary>
    /// A geo-tag
    /// </summary>
    [Table("geo_tbl")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class DbGeoTag : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [PrimaryKey, Column("geo_id"), AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Latitude
        /// </summary>
        [Column("lat"), NotNull]
        public double Lat { get; set; }

        /// <summary>
        /// Longitude
        /// </summary>
        [Column("lng"), NotNull]
        public double Lng { get; set; }
    }
}