copy \Users\fyfej\source\repos\santedb\santedb-server-v3\bin\Debug\SanteDB.Persistence.Data.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\restsrvr\RestSrvr\bin\Debug\RestSrvr.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-api\bin\Debug\SanteDB.Core.Api.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-applets\bin\Debug\SanteDB.Core.Applets.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-bis\bin\Debug\SanteDB.BI.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-bis\SanteDB.Rest.BIS\bin\Debug\SanteDB.Rest.BIS.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-bre-js\bin\Debug\SanteDB.BusinessRules.JavaScript.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-cache-memory\bin\Debug\SanteDB.Caching.Memory.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-cache-redis\bin\Debug\SanteDB.Caching.Redis.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-cdss\bin\Debug\SanteDB.Cdss.Xml.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-docker\SanteDB.Docker.Core\bin\Debug\SanteDB.Docker.Core.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-fhir\bin\Debug\SanteDB.Messaging.FHIR.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-hl7\bin\Debug\SanteDB.Messaging.HL7.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-i18n\SanteDB.Core.i18n\bin\Debug\SanteDB.Core.i18n.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-match\SanteDB.Matcher\bin\Debug\SanteDB.Matcher.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-mdm\bin\Debug\SanteDB.Persistence.MDM.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-model\bin\Debug\SanteDB.Core.Model.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-openapi\bin\Debug\SanteDB.Messaging.Metadata.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-orm\bin\Debug\SanteDB.OrmLite.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\bin\Debug\SanteDB.Core.Model.AMI.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\bin\Debug\SanteDB.Core.Model.RISI.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\bin\Debug\SanteDB.Core.Model.ViewModelSerializers.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\SanteDB.Rest.AMI\bin\Debug\SanteDB.Rest.AMI.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\SanteDB.Rest.Common\bin\Debug\SanteDB.Rest.Common.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\SanteDB.Rest.HDSI\bin\Debug\SanteDB.Rest.HDSI.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\SanteDB.Rest.WWW\bin\Debug\SanteDB.Rest.WWW.1.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\santedb-restsvc\SanteDB.Rest.WWW\bin\Debug\SanteDB.Rest.WWW.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\SanteDB.Core.TestFramework\bin\Debug\SanteDB.Core.TestFramework.3.0.0.* %localappdata%\nugetstaging
copy \Users\fyfej\source\repos\santedb\santedb-server-v3\SanteDB.Persistence.PubSub.ADO\bin\Debug\SanteDB.Persistence.PubSub.ADO.2.1.3.* %localappdata%\nugetstaging
