using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Auditing.ADO.Data.Model
{
    /// <summary>
    /// Audit metadata values
    /// </summary>
    [Table("aud_meta_val_cdtbl")]
    public class DbAuditMetadataValue
    {

        /// <summary>
        /// Gets the key
        /// </summary>
        [Column("val_id"), PrimaryKey, AutoGenerated]
        public long Key { get; set; }

        /// <summary>
        /// Gets the value
        /// </summary>
        [Column("val"), NotNull]
        public String Value { get; set; }

    }
}
