using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Auditing.ADO.Data.Model
{
    /// <summary>
    /// Audit metadata
    /// </summary>
    [Table("aud_meta_tbl")]
    public class DbAuditMetadata 
    {
        /// <summary>
        /// Identifier of the object
        /// </summary>
        [Column("id"), PrimaryKey, AutoGenerated]
        public Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the audit identifier
        /// </summary>
        [Column("aud_id"), ForeignKey(typeof(DbAuditData), nameof(DbAuditData.Key))]
        public Guid AuditId { get; set; }

        /// <summary>
        /// Metadata key for audits
        /// </summary>
        [Column("attr")]
        public int MetadataKey { get; set; }

        /// <summary>
        /// The value of the audit metadata
        /// </summary>
        [Column("val")]
        public string Value { get; set; }
    }
}
