using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Configuration
{
    /// <summary>
    /// Data quality ruleset
    /// </summary>
    [Table("cnf_dq")]
    public class DbDataQualityRuleset : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the key of this object
        /// </summary>
        [Column("cnf_id"), NotNull, AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the identifier of this configuration
        /// </summary>
        [Column("pub_id"), NotNull]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the configuration
        /// </summary>
        [Column("name"), NotNull]
        public string Name { get; set; }

        /// <summary>
        /// True if the configuration is enabled
        /// </summary>
        [Column("enabled"), NotNull]
        public bool Enabled { get; set; }

        /// <summary>
        /// The configuration for the ruleset
        /// </summary>
        [Column("conf"), NotNull]
        public byte[] Configuration { get; set; }
    }
}
