using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Configuration
{
    /// <summary>
    /// Match configuration table
    /// </summary>
    [Table("cnf_match")]
    public class DbMatchConfiguration : DbNonVersionedBaseData
    {

        /// <summary>
        /// Configuration identification
        /// </summary>
        [Column("cnf_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the name of the configuration
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Configuration data
        /// </summary>
        [Column("config"), NotNull]
        public byte[] ConfigurationData { get; set; }
    }
}
