<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.Net.Sdk">
  <PropertyGroup Condition="'$(VersionNumber)' == ''">
    <VersionNumber>3.0-debug</VersionNumber>
  </PropertyGroup>
  <Choose>
    <When Condition="$(VersionNumber.Contains('-'))">
      <PropertyGroup>
        <VersionNumberInfo>$(VersionNumber.Substring(0, $(VersionNumber.IndexOf('-'))))</VersionNumberInfo>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <VersionNumberInfo>$(VersionNumber)</VersionNumberInfo>
      </PropertyGroup>
    </Otherwise>
  </Choose>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>SanteDB.Messaging.Atna</PackageId>
		<Title>SanteDB Server ATNA Audit Shipping Support</Title>
		<Version>$(VersionNumber)</Version>
		<Description>Allows the shipping of audit using IETF RFC3881 or DICOM format audits from SanteDB</Description>
		<Authors>SanteDB Community</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-server</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
		<PackageTags>atna santedb server</PackageTags>
	</PropertyGroup>
  <Choose>
    <When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Docker.Core" Version="$(VersionNumber)" />
			</ItemGroup>
    </When>
    <Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
				<ProjectReference Include="..\santedb-docker\SanteDB.Docker.Core\SanteDB.Docker.Core.csproj" />
			</ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
    <None Include="..\SanteDB.licenseheader">
      <Link>SanteDB.licenseheader</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AtnaApi.NetStandard" Version="1.2.2" />
  </ItemGroup>
</Project>