using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Mail
{
    /// <summary>
    /// Mailbox to Mail message association
    /// </summary>
    [Table("mail_box_msg_assoc_tbl")]
    public class DbMailboxMessageAssociation : DbAssociation
    {

        /// <summary>
        /// Gets or sets the key of the mailbox association
        /// </summary>
        [Column("mail_box_msg_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// The source of the relationship
        /// </summary>
        [Column("mail_box_id"), ForeignKey(typeof(DbMailbox), nameof(DbMailbox.Key)), NotNull]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets the target key for the relationship
        /// </summary>
        [Column("mail_msg_id"), ForeignKey(typeof(DbMailMessage), nameof(DbMailMessage.Key))]
        public Guid TargetKey { get; set; }

        /// <summary>
        /// Gets or sets the mail status
        /// </summary>
        [Column("sts"), NotNull]
        public int MailStatusFlag { get; set; }
    }
}
