/*
 * Copyright (C) 2021 - 2022, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: fyfej
 * Date: 2022-9-7
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Data.Model.Security
{
    /// <summary>
    /// Defines a security challenge question for the user
    /// </summary>
    [Table("sec_chl_tbl")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class DbSecurityChallenge : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the key of the challenge
        /// </summary>
        [Column("chl_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the challenge text
        /// </summary>
        [Column("chl_txt")]
        public String ChallengeText { get; set; }

    }


    /// <summary>
    /// Security user challenge association
    /// </summary>
    [Table("sec_usr_chl_assoc_tbl")]
    public class DbSecurityUserChallengeAssoc
    {

        /// <summary>
        /// Gets the user that is associated with this challenge
        /// </summary>
        [Column("usr_id"), ForeignKey(typeof(DbSecurityUser), nameof(DbSecurityUser.Key))]
        public Guid UserKey { get; set; }

        /// <summary>
        /// Gets or sets the associated challenge text
        /// </summary>
        [Column("chl_id")]
        public Guid ChallengeKey { get; set; }

        /// <summary>
        /// Challenge response
        /// </summary>
        [Column("chl_rsp"), Secret]
        public String ChallengeResponse { get; set; }

        /// <summary>
        /// The time that the challenge will expire
        /// </summary>
        [Column("exp_utc")]
        public DateTimeOffset ExpiryTime { get; set; }

    }
}
