/*
 * Copyright (C) 2021 - 2022, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: fyfej
 * Date: 2022-9-7
 */
using SanteDB.OrmLite;
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteDB.Persistence.Data.Model
{
    /// <summary>
    /// Represents identified data
    /// </summary>

    public interface IDbIdentified
    {
        /// <summary>
        /// Gets or sets the key of the object
        /// </summary>
        Guid Key { get; set; }
    }

    /// <summary>
    /// Gets or sets the identified data
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public abstract class DbIdentified : IDbIdentified
    {
     

        /// <summary>
        /// Gets or sets the key of the object
        /// </summary>
        [AutoGenerated]
        public abstract Guid Key { get; set; }

        /// <summary>
        /// Return whether the object has value equality
        /// </summary>
        public override bool Equals(object obj)
        {
            if(obj is DbIdentified dbi)
            {
                return dbi.Key.Equals(this.Key);
            }
            return base.Equals(obj);
        }

        /// <summary>
        /// Represent this object as a string 
        /// </summary>
        public override string ToString() => $"{this.GetType().Name} (K:{this.Key})";
    }

    
}
