<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.SDk">
  <PropertyGroup Condition="'$(VersionNumber)' == ''">
    <VersionNumber>3.0-debug</VersionNumber>
  </PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>SanteDB.iCDR.Configuration</PackageId>
		<Title>SanteDB Configuration Tool Library</Title>
		<Version>$(VersionNumber)</Version>
		<Description>Allows developers to write configuration panel extensions for the ConfigTool used by the SanteDB iCDR server.</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-api</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>
  <Choose>
    <When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="RestSrvr" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Applets" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.BI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Cdss.Xml" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.OrmLite" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.Common" Version="$(VersionNumber)" />
			</ItemGroup>
    </When>
    <Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
				<ProjectReference Include="..\restsrvr\RestSrvr\RestSrvr.csproj" />
				<ProjectReference Include="..\santedb-applets\SanteDB.Core.Applets\SanteDB.Core.Applets.csproj" />
				<ProjectReference Include="..\santedb-bis\SanteDB.BI\SanteDB.BI.csproj" />
				<ProjectReference Include="..\santedb-cdss\SanteDB.Cdss.Xml\SanteDB.Cdss.Xml.csproj" />
				<ProjectReference Include="..\santedb-orm\SanteDB.OrmLite\SanteDB.OrmLite.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.Common\SanteDB.Rest.Common.csproj" />
			</ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
    <None Include="..\SanteDB.licenseheader">
      <Link>SanteDB.licenseheader</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Design" />
    <Reference Include="System.Security" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>