<Project Sdk="Microsoft.Net.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)'==''">
		<VersionNumber>3.0-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Server.Core" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
			  <ProjectReference Include="..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
			  <ProjectReference Include="..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
			  <ProjectReference Include="..\SanteDB.Core\SanteDB.Server.Core.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>
	<ItemGroup>
		<None Include="..\SanteDB.licenseheader">
			<Link>SanteDB.licenseheader</Link>
		</None>
	</ItemGroup>
</Project>