using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.Model.Concepts;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.System
{
    /// <summary>
    /// Generic definition for an entity relationship validation table
    /// </summary>
    public abstract class DbRelationshipValidationRule
    {
        /// <summary>
        /// Primary key for the validation rule
        /// </summary>
        [AutoGenerated]
        public abstract Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the relationship type key
        /// </summary>
        [Column("rel_typ_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid RelationshipTypeKey { get; set; }

        /// <summary>
        /// Gets or sets the source classification code key
        /// </summary>
        [Column("src_cls_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid SourceClassKey { get; set; }

        /// <summary>
        /// Gets or sets the target class code key
        /// </summary>
        [Column("trg_cls_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid TargetClassKey { get; set; }

        /// <summary>
        /// Gets or sets the description or documentation for the relationship
        /// </summary>
        [Column("err_desc")]
        public String Description { get; set; }
    }

    /// <summary>
    /// Entity --> Entity relationship validations
    /// </summary>
    [Table("ent_rel_vrfy_cdtbl")]
    public class DbEntityRelationshipValidationRule : DbRelationshipValidationRule
    {
        /// <summary>
        /// Gets or sets the entity primary key
        /// </summary>
        [Column("ent_rel_vrfy_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }
    }

    /// <summary>
    /// Act --> Act relationship validations
    /// </summary>
    [Table("act_rel_vrfy_cdtbl")]
    public class DbActRelationshipValidationRule : DbRelationshipValidationRule
    {
        /// <summary>
        /// Gets or sets the entity primary key
        /// </summary>
        [Column("act_rel_vrfy_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }
    }

    /// <summary>
    /// Act --> Entity relationship validations
    /// </summary>
    [Table("act_ptcpt_vrfy_cdtbl")]
    public class DbActParticipationValidationRule : DbRelationshipValidationRule
    {
        /// <summary>
        /// Gets or sets the entity primary key
        /// </summary>
        [Column("act_ptcpt_vrfy_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }
    }
}
