/** 
 * <feature scope="SanteDB.Persistence.Data" id="20220530-01" name="Update:20220530-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="FirebirdSQL">
 *	<summary>Update: Adds certificate authentication provider tables. Adds messaging mailbox tables</summary>
 *	<isInstalled>select ck_patch('20220530-01') from RDB$DATABASE</isInstalled>
 * </feature>
 */

 -- CERTIFICATE AUTHENTICAITON INFORMATION
 CREATE TABLE SEC_CER_TBL (
	CER_ID UUID NOT NULL, 
	X509_THB VARCHAR(64) NOT NULL, -- THE X509 CERTIFICATE THUMBPRINT IDENTIFIER
	X509_PK BLOB NOT NULL, -- X509 contents
	EXP_UTC TIMESTAMP NOT NULL, -- THE EXPIRATION OF THE CERTIFICATE (HELPS WITH DATABASE CALLS)
	CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CRT_PROV_ID UUID,
	OBSLT_UTC TIMESTAMP,
	OBSLT_PROV_ID UUID,
	UPD_UTC TIMESTAMP,
	UPD_PROV_ID UUID,
	USR_ID UUID,
	APP_ID UUID,
	DEV_ID UUID,
	CONSTRAINT PK_SEC_CER_AUTH_TBL PRIMARY KEY (CER_ID),
	CONSTRAINT FK_SEC_CER_CRT_PROV FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_SEC_CER_UPD_PROV FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_SEC_CER_OBSLT_PROV FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_SEC_CER_USR_ID FOREIGN KEY (USR_ID) REFERENCES SEC_USR_TBL(USR_ID),
	CONSTRAINT FK_SEC_CER_APP_ID FOREIGN KEY (APP_ID) REFERENCES SEC_APP_TBL(APP_ID),
	CONSTRAINT FK_SEC_CER_DEV_ID FOREIGN KEY (DEV_ID) REFERENCES SEC_DEV_TBL(DEV_ID),
	CONSTRAINT FK_SEC_CER_MAP CHECK (
		USR_ID IS NOT NULL AND APP_ID IS NULL AND DEV_ID IS NULL OR 
		USR_ID IS NULL AND APP_ID IS NOT NULL AND DEV_ID IS NULL OR
		USR_ID IS NULL AND APP_ID IS NULL AND DEV_ID IS NOT NULL
	)
 );--#!

 CREATE UNIQUE INDEX SEC_CER_X509_THB_IDX ON SEC_CER_TBL COMPUTED BY (CASE WHEN OBSLT_UTC IS NULL THEN X509_THB ELSE NULL END);--#!

 ALTER TABLE PAT_TBL DROP CONSTRAINT INTEG_285;--#!
 ALTER TABLE PAT_TBL ADD CONSTRAINT CK_DCSD_PREC CHECK (DCSD_PREC IN ('Y','m', 'D'));--#!
 ALTER TABLE PSN_TBL DROP CONSTRAINT INTEG_277;--#!
 ALTER TABLE PSN_TBL ADD CONSTRAINT CK_DOB_PREC CHECK (DOB_PREC IN ('Y','m','D'));--#!

 CREATE TABLE id_dmn_tbl (
 	DMN_ID UUID NOT NULL,
	DMN_NAME VARCHAR(50) NOT NULL, -- THE NAME OF THE ASSIGNING AUTHORITY
	OID VARCHAR(196) NOT NULL, -- THE OID OF THE ASSIGNING AUTHORTIY
	NSID VARCHAR(32) NOT NULL, -- THE HL7 V2 CX.4 ASSIGNING AUTHORITY DOMAIN
	URL VARCHAR(250), -- THE URL OF THE ASSINGING AUTHORITY DEFINITION
	DESCR BLOB SUB_TYPE TEXT, -- THE DESCRIPTION OF THE AUTHORITY
	CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- THE TIME THAT THE AA WAS CREATED
	CRT_PROV_ID UUID NOT NULL, -- THE USER WHICH CREATED THE AA
	OBSLT_UTC TIMESTAMP, -- THE TIME THAT THE AA WAS OBSOLETED
	OBSLT_PROV_ID UUID, -- THE USER WHICH OBSOLETED THE AA
	UPD_UTC TIMESTAMP, -- TIME THAT WAS UPDATED
	UPD_PROV_ID UUID, -- USER WHICH UPDATED
	VAL_RGX VARCHAR(64), -- REGULAR EXPRESSION FOR VALIDATION
	POL_ID  UUID, -- POLICY ID
	VAL_CLS VARCHAR(256), -- VALIDATOR CLASS
	IS_UNQ BOOLEAN DEFAULT FALSE NOT NULL, -- TRUE IF THE ASSIGNING AUTHORITY IS UNIQUE
	CONSTRAINT PK_ID_DMN_TBL PRIMARY KEY (DMN_ID),
	CONSTRAINT FK_ID_DMN_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_ID_DMN_UPD_PROV_ID FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_ID_DMN_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_ID_DMN_POL_ID FOREIGN KEY (POL_ID) REFERENCES SEC_POL_TBL (POL_ID), 
	CONSTRAINT CK_ID_DMN_OBSLT_PROV_ID CHECK (OBSLT_PROV_ID IS NOT NULL AND OBSLT_UTC IS NOT NULL OR OBSLT_PROV_ID IS NULL AND OBSLT_UTC IS NULL)
);
--#!
CREATE UNIQUE INDEX ID_DMN_NAME_IDX ON ID_DMN_TBL(NSID);
--#!
CREATE UNIQUE INDEX ID_DMN_OID_IDX ON ID_DMN_TBL(OID);
--#!
INSERT INTO ID_DMN_TBL (DMN_ID, DMN_NAME, OID, NSID, URL, DESCR, CRT_UTC, CRT_PROV_ID, OBSLT_UTC, OBSLT_PROV_ID, UPD_UTC, UPD_PROV_ID, VAL_RGX, IS_UNQ, POL_ID, VAL_CLS) SELECT AUT_ID, AUT_NAME, OID, NSID, URL, DESCR, CRT_UTC, CRT_PROV_ID, OBSLT_UTC, OBSLT_PROV_ID, UPD_UTC, UPD_PROV_ID, VAL_RGX, IS_UNQ, POL_ID, VAL_CLS FROM ASGN_AUT_TBL;
--#!

-- IDENTIFIES SCOPES TO WHICH AN AA APPLIES
CREATE TABLE ID_DMN_SCP_TBL (
	DMN_ID UUID NOT NULL, -- THE AA TO WHICH THE SCOPE APPLIES
	CD_ID UUID NOT NULL, -- THE CHAR(16) FOR THE CLASS WHICH DESCRIBES THE SCOPE
	CONSTRAINT PK_ID_DMN_SCP_TBL PRIMARY KEY (DMN_ID, CD_ID),
	CONSTRAINT FK_ID_DMN_SCP_AUT_ID FOREIGN KEY (DMN_ID) REFERENCES ID_DMN_TBL(DMN_ID),
	CONSTRAINT FK_ID_DMN_SCP_CD_ID FOREIGN KEY (CD_ID) REFERENCES CD_TBL(CD_ID)
);--#!
INSERT INTO ID_DMN_SCP_TBL SELECT * FROM ASGN_AUT_SCP_TBL;--#!
DROP TABLE ASGN_AUT_SCP_TBL;--#!
ALTER TABLE ENT_ID_TBL ADD DMN_ID UUID; --#!
ALTER TABLE ENT_ID_TBL ADD CONSTRAINT FK_ENT_ID_DMN_ID FOREIGN KEY (DMN_ID) REFERENCES ID_DMN_TBL(DMN_ID); --#!
UPDATE ENT_ID_TBL SET DMN_ID = AUT_ID;--#!
ALTER TABLE ENT_ID_TBL ALTER DMN_ID SET NOT NULL; --#!
DROP FUNCTION IS_ENT_ID_UNQ;--#!
ALTER TABLE ENT_ID_TBL DROP AUT_ID;--#!

ALTER TABLE ACT_ID_TBL ADD DMN_ID UUID; --#!
ALTER TABLE ACT_ID_TBL ADD CONSTRAINT FK_ACT_ID_DMN_ID FOREIGN KEY (DMN_ID) REFERENCES ID_DMN_TBL(DMN_ID); --#!
UPDATE ACT_ID_TBL SET DMN_ID = AUT_ID;--#!
ALTER TABLE ACT_ID_TBL ALTER DMN_ID SET NOT NULL; --#!
ALTER TABLE ACT_ID_TBL DROP AUT_ID;--#!
ALTER TABLE ENT_ID_TBL ADD REL INT DEFAULT 0 NOT NULL; --#!
ALTER TABLE ACT_ID_TBL ADD REL INT DEFAULT 0 NOT NULL; --#!
DROP TABLE ASGN_AUT_TBL;--#!

CREATE TABLE ASGN_AUT_TBL (
	AUT_ID UUID NOT NULL,
	DMN_ID UUID NOT NULL, -- IDENTITY DOMAIN
	APP_ID UUID NOT NULL, -- APPLICATION ALLOWED TO ASSIGN
	CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- THE TIME THAT THE AA WAS CREATED
	CRT_PROV_ID UUID NOT NULL, -- THE USER WHICH CREATED THE AA
	OBSLT_UTC TIMESTAMP, -- THE TIME THAT THE AA WAS OBSOLETED
	OBSLT_PROV_ID UUID, -- THE USER WHICH OBSOLETED THE AA
	REL INT DEFAULT 0 NOT NULL, -- RELIABILITY,
	CONSTRAINT PK_ASGN_AUT_TBL PRIMARY KEY (AUT_ID),
	CONSTRAINT FK_ASGN_AUT_DMN_TBL FOREIGN KEY (DMN_ID) REFERENCES ID_DMN_TBL (DMN_ID),
	CONSTRAINT FK_ASGN_AUT_APP_TBL FOREIGN KEY (APP_ID) REFERENCES SEC_APP_TBL (APP_ID),
	CONSTRAINT FK_ASGN_AUT_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_ASGN_AUT_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT CK_ASGN_AUT_REL CHECK (REL >= 0 AND REL <= 4)
);--#!
CREATE UNIQUE INDEX ASGN_AUT_TBL_UQ_IDX ON ASGN_AUT_TBL(DMN_ID, APP_ID);--#!

CREATE TABLE MAIL_BOX_TBL (
	MAIL_BOX_ID UUID NOT NULL, -- MAILBOX ID
	OWN_ID UUID NOT NULL, -- THE OWNER OF THIS MAILBOX
	NAME VARCHAR(32) NOT NULL, -- THE NAME OF THE MAILBOX
	CRT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- THE TIME THAT THE AA WAS CREATED
	CRT_PROV_ID UUID NOT NULL, -- THE USER WHICH CREATED THE AA
	OBSLT_UTC TIMESTAMP, -- THE TIME THAT THE AA WAS OBSOLETED
	OBSLT_PROV_ID UUID, -- THE USER WHICH OBSOLETED THE AA
	CONSTRAINT PK_MAIL_BOX_TBL PRIMARY KEY (MAIL_BOX_ID),
	CONSTRAINT FK_MAIL_BOX_OWNER FOREIGN KEY (OWN_ID) REFERENCES SEC_USR_TBL(USR_ID),
	CONSTRAINT FK_MAIL_BOX_CRT_PROV_ID FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_MAIL_BOX_OBSLT_PROV_ID FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID)
); --#!
CREATE INDEX MAIL_BOX_OWN_IDX ON MAIL_BOX_TBL(OWN_ID);--#!
CREATE TABLE MAIL_BOX_MSG_ASSOC_TBL (
	MAIL_BOX_MSG_ID UUID NOT NULL,
	MAIL_BOX_ID UUID NOT NULL,
	MAIL_MSG_ID UUID NOT NULL,
	STS INT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_MAIL_BOX_MSG_TBL PRIMARY KEY (MAIL_BOX_MSG_ID),
	CONSTRAINT FK_MAIL_BOX_MSG_BOX_ID FOREIGN KEY (MAIL_BOX_ID) REFERENCES MAIL_BOX_TBL (MAIL_BOX_ID),
	CONSTRAINT FK_MAIL_BOX_MSG_MSG_ID FOREIGN KEY (MAIL_MSG_ID) REFERENCES MAIL_MSG_TBL (MAIL_MSG_ID)
); --#!
SELECT REG_PATCH('20220530-01') FROM RDB$DATABASE; --#!

