/** 
 * <feature scope="SanteDB.Persistence.Data" id="20220530-01" name="Update:20220530-01" applyRange="1.1.0.0-1.2.0.0"  invariantName="npgsql">
 *	<summary>Update: Adds certificate authentication provider tables</summary>
 *	<isInstalled>select ck_patch('20220530-01')</isInstalled>
 * </feature>
 */

 -- CERTIFICATE AUTHENTICAITON INFORMATION
 CREATE TABLE SEC_CER_TBL (
	CER_ID UUID NOT NULL DEFAULT GENERATE_UUID_V1(), 
	X509_THB VARCHAR(32) NOT NULL, -- THE X509 CERTIFICATE THUMBPRINT IDENTIFIER
	X509_PK BYTEA NOT NULL, -- X509 PUBLIC KEY CERTIFICATE DATA
	EXP_UTC TIMESTAMPTZ NOT NULL, -- THE EXPIRATION OF THE CERTIFICATE (HELPS WITH DATABASE CALLS)
	CRT_UTC TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CRT_PROV_ID UUID,
	OBSLT_UTC TIMESTAMPTZ,
	OBSLT_PROV_ID UUID,
	UPD_UTC TIMESTAMPTZ,
	UPD_PROV_ID UUID,
	USR_ID UUID,
	APP_ID UUID,
	DEV_ID UUID,
	CONSTRAINT PK_SEC_CER_AUTH_TBL PRIMARY KEY (CER_ID),
	CONSTRAINT FK_SEC_CER_CRT_PROV FOREIGN KEY (CRT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_SEC_CER_UPD_PROV FOREIGN KEY (UPD_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_SEC_CER_OBSLT_PROV FOREIGN KEY (OBSLT_PROV_ID) REFERENCES SEC_PROV_TBL(PROV_ID),
	CONSTRAINT FK_SEC_CER_USR_ID FOREIGN KEY (USR_ID) REFERENCES SEC_USR_TBL(USR_ID),
	CONSTRAINT FK_SEC_CER_APP_ID FOREIGN KEY (APP_ID) REFERENCES SEC_APP_TBL(APP_ID),
	CONSTRAINT FK_SEC_CER_DEV_ID FOREIGN KEY (DEV_ID) REFERENCES SEC_DEV_TBL(DEV_ID),
	CONSTRAINT FK_SEC_CER_MAP CHECK (
		USR_ID IS NOT NULL AND APP_ID IS NULL AND DEV_ID IS NULL OR 
		USR_ID IS NULL AND APP_ID IS NOT NULL AND DEV_ID IS NULL OR
		USR_ID IS NULL AND APP_ID IS NULL AND DEV_ID IS NOT NULL
	)
 )--#!

 CREATE UNIQUE INDEX SEC_CER_X509_THB_IDX ON SEC_CER_TBL(X509_THB) WHERE (OBSLT_UTC IS NULL);--#!

SELECT REG_PATCH('20220509-01'); --#!