using SanteDB.OrmLite.Attributes;
using SanteDB.Persistence.Data.Model.Concepts;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.Data.Model.Sys
{

    /// <summary>
    /// Relationship target type
    /// </summary>
    public enum RelationshipTargetType
    {
        /// <summary>
        /// Entity-Entity
        /// </summary>
        EntityRelationship = 1,
        /// <summary>
        /// Act-Act
        /// </summary>
        ActRelationship = 2,
        /// <summary>
        /// Act-Entity
        /// </summary>
        ActParticipation = 3
    }

    /// <summary>
    /// Generic definition for an entity relationship validation table
    /// </summary>
    [Table("rel_vrfy_systbl")]
    public class DbRelationshipValidationRule
    {
        /// <summary>
        /// Primary key for the validation rule
        /// </summary>
        [Column("rel_vrfy_id"), PrimaryKey, AutoGenerated]
        public Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the relationship type key
        /// </summary>
        [Column("rel_typ_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid RelationshipTypeKey { get; set; }

        /// <summary>
        /// Gets or sets the source classification code key
        /// </summary>
        [Column("src_cls_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid SourceClassKey { get; set; }

        /// <summary>
        /// Gets or sets the target class code key
        /// </summary>
        [Column("trg_cls_cd_id"), ForeignKey(typeof(DbConcept), nameof(DbConcept.Key))]
        public Guid TargetClassKey { get; set; }

        /// <summary>
        /// Gets or sets the description or documentation for the relationship
        /// </summary>
        [Column("err_desc")]
        public String Description { get; set; }

        /// <summary>
        /// Target class
        /// </summary>
        [Column("rel_cls")]
        public RelationshipTargetType RelationshipClassType { get; set; }
 
    }

}