using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Security
{
    /// <summary>
    /// Defines a security challenge question for the user
    /// </summary>
    [Table("sec_chl_tbl")]
    public class DbSecurityChallenge : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the key of the challenge
        /// </summary>
        [Column("chl_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the challenge text
        /// </summary>
        [Column("chl_txt")]
        public String ChallengeText { get; set; }

    }


    /// <summary>
    /// Security user challenge association
    /// </summary>
    [Table("sec_usr_chl_assoc_tbl")]
    public class DbSecurityUserChallengeAssoc
    {

        /// <summary>
        /// Gets the user that is associated with this challenge
        /// </summary>
        [Column("usr_id"), ForeignKey(typeof(DbSecurityUser), nameof(DbSecurityUser.Key))]
        public Guid UserKey { get; set; }

        /// <summary>
        /// Gets or sets the associated challenge text
        /// </summary>
        [Column("chl_id")]
        public Guid ChallengeKey { get; set; }

        /// <summary>
        /// Challenge response
        /// </summary>
        [Column("chl_rsp"), Secret]
        public String ChallengeResponse { get; set; }

        /// <summary>
        /// The time that the challenge will expire
        /// </summary>
        [Column("exp_utc")]
        public DateTime ExpiryTime { get; set; }

    }
}
