using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteDB.Persistence.Data.ADO.Data.Model.Security
{
    /// <summary>
    /// Represents simple provenance
    /// </summary>
    [Table("sec_prov_tbl")]
    public class DbSecurityProvenance : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key field
        /// </summary>
        [Column("prov_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the application id
        /// </summary>
        [Column("app_id"), NotNull, ForeignKey(typeof(DbSecurityApplication), nameof(DbSecurityApplication.Key))]
        public Guid ApplicationKey { get; set; }

        /// <summary>
        /// Gets or sets the user id
        /// </summary>
        [Column("usr_id"), ForeignKey(typeof(DbSecurityUser), nameof(DbSecurityUser.Key))]
        public Guid? UserKey { get; set; }

        /// <summary>
        /// Gets or sets the device key
        /// </summary>
        [Column("dev_id"), ForeignKey(typeof(DbSecurityDevice), nameof(DbSecurityDevice.Key))]
        public Guid? DeviceKey { get; set; }

        /// <summary>
        /// Gets or sets the session key
        /// </summary>
        [Column("ses_id")]
        public Guid? SessionKey { get; set; }
    }
}
