/*
 * Copyright (C) 2021 - 2022, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: fyfej
 * Date: 2022-5-30
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.PubSub.ADO.Data.Model
{
    /// <summary>
    /// Represents a base object
    /// </summary>
    public abstract class DbBaseObject
    {
        /// <summary>
        /// Gets or sets the identifier of the object
        /// </summary>
        [AutoGenerated]
        public abstract Guid? Key { get; set; }

        /// <summary>
        /// Gets or sets the creation time
        /// </summary>
        [Column("crt_utc"), NotNull, AutoGenerated]
        public DateTimeOffset CreationTime { get; set; }

        /// <summary>
        /// Gets the user which created the object
        /// </summary>
        [Column("crt_usr_id"), NotNull]
        public Guid CreatedByKey { get; set; }

        /// <summary>
        /// Gets the time the data was updated
        /// </summary>
        [Column("upd_utc")]
        public DateTimeOffset? UpdatedTime { get; set; }

        /// <summary>
        /// Updated by key
        /// </summary>
        [Column("upd_usr_id")]
        public Guid? UpdatedByKey { get; set; }

        /// <summary>
        /// Gets the obsoletion time
        /// </summary>
        [Column("obslt_utc")]
        public DateTimeOffset? ObsoletionTime { get; set; }

        /// <summary>
        /// Obsoletion user
        /// </summary>
        [Column("obslt_usr_id")]
        public Guid? ObsoletedByKey { get; set; }


        /// <summary>
        /// True if the object is active
        /// </summary>
        [Column("is_act"), NotNull]
        public bool IsActive { get; set; }


        /// <summary>
        /// True if explicitly set obsolete to null
        /// </summary>
        public bool ObsoletedBySpecified { get; set; }
        /// <summary>
        /// True if explicitly set obsolete to null
        /// </summary>
        public bool ObsoletionTimeSpecified { get; set; }
    }
}
