using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.PubSub.ADO.Data.Model
{
    /// <summary>
    /// Represents a database representation of a channel
    /// </summary>
    [Table("sub_chnl_tbl")]
    public class DbChannel : DbBaseObject
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("chnl_id"), NotNull, AutoGenerated, PrimaryKey]
        public override Guid? Key { get; set; }

        /// <summary>
        /// Gets or sets the name
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the endpoint
        /// </summary>
        [Column("uri"), NotNull]
        public String Endpoint { get; set; }

        /// <summary>
        /// Gets or sets the dispatcher
        /// </summary>
        [Column("dsptchr_cls"), NotNull]
        public String DispatchFactoryType { get; set; }
    }
}
