using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.PubSub.ADO.Data.Model
{
    /// <summary>
    /// Represents a subscription definition
    /// </summary>
    [Table("sub_tbl")]
    public class DbSubscription : DbBaseObject
    {
        /// <summary>
        /// Gets or sets the subscription key
        /// </summary>
        [Column("sub_id"), NotNull, AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Name of the subscription
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// The effective time of the sub
        /// </summary>
        [Column("nbf")]
        public DateTimeOffset? NotBefore { get; set; }

        /// <summary>
        /// The time of stop
        /// </summary>
        [Column("naf")]
        public DateTimeOffset? NotAfter { get; set; }

        /// <summary>
        /// Resource type
        /// </summary>
        [Column("rsrc_cls"), NotNull]
        public String ResourceType { get; set; }

        /// <summary>
        /// The event
        /// </summary>
        [Column("evt_id"),NotNull]
        public int Event { get; set; }

        /// <summary>
        /// Channel key
        /// </summary>
        [Column("chnl_id"), NotNull, ForeignKey(typeof(DbChannel), nameof(DbChannel.Key))]
        public Guid ChannelKey { get; set; }
    }
}
