/*
 * Copyright (C) 2021 - 2022, SanteSuite Inc. and the SanteSuite Contributors (See NOTICE.md for full copyright notices)
 * Copyright (C) 2019 - 2021, Fyfe Software Inc. and the SanteSuite Contributors
 * Portions Copyright (C) 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * User: fyfej
 * Date: 2022-5-30
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace SanteDB.Persistence.PubSub.ADO.Data.Model
{
    /// <summary>
    /// Represents a subscription definition
    /// </summary>
    [Table("sub_tbl")]
    public class DbSubscription : DbBaseObject
    {
        /// <summary>
        /// Gets or sets the subscription key
        /// </summary>
        [Column("sub_id"), NotNull, AutoGenerated, PrimaryKey]
        public override Guid? Key { get; set; }

        /// <summary>
        /// Name of the subscription
        /// </summary>
        [Column("name"), NotNull]
        public String Name { get; set; }

        /// <summary>
        /// Description of the subscription
        /// </summary>
        [Column("note")]
        public String Description { get; set; }

        /// <summary>
        /// Gets the support contact
        /// </summary>
        [Column("spprt")]
        public String SupportContact { get; set; }

        /// <summary>
        /// The effective time of the sub
        /// </summary>
        [Column("nbf")]
        public DateTimeOffset? NotBefore { get; set; }

        /// <summary>
        /// The time of stop
        /// </summary>
        [Column("naf")]
        public DateTimeOffset? NotAfter { get; set; }

        /// <summary>
        /// Resource type
        /// </summary>
        [Column("rsrc_cls"), NotNull]
        public String ResourceType { get; set; }

        /// <summary>
        /// The event
        /// </summary>
        [Column("evt_id"),NotNull]
        public int Event { get; set; }

        /// <summary>
        /// Channel key
        /// </summary>
        [Column("chnl_id"), NotNull, ForeignKey(typeof(DbChannel), nameof(DbChannel.Key))]
        public Guid ChannelKey { get; set; }
    }
}
