<Project Sdk="Microsoft.Net.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)'==''">
		<VersionNumber>3.0-debug</VersionNumber>
	</PropertyGroup>
	<Choose>
		<When Condition="$(VersionNumber.Contains('-'))">
			<PropertyGroup>
				<VersionNumberInfo>$(VersionNumber.Substring(0, $(VersionNumber.IndexOf('-'))))</VersionNumberInfo>
			</PropertyGroup>
		</When>
		<Otherwise>
			<PropertyGroup>
				<VersionNumberInfo>$(VersionNumber)</VersionNumberInfo>
			</PropertyGroup>
		</Otherwise>
	</Choose>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<PropertyGroup>
		<Version>$(VersionNumber)</Version>
		<RootNamespace>SanteDB</RootNamespace>
		<AssemblyName>SanteDB</AssemblyName>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<Title>SanteDB iCDR</Title>
		<Description>SanteDC Integrated Clinical Data Repository</Description>
	</PropertyGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="RestSrvr" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Applets" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.Common" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.OrmLite" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.BI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.BIS" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.BusinessRules.JavaScript" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Cdss.Xml" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Matcher" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Matcher.Configuration.File" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model.AMI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model.RISI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.AMI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.HDSI" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model.ViewModelSerializers" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Queue.Msmq" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Persistence.Data" Version="$(VersionNumber)" />

				<PackageReference Include="SanteDB.Caching.Memory" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Caching.Redis" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Security.Certs.BouncyCastle" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Persistence.Auditing.ADO" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Persistence.PubSub.ADO" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Persistence.Synchronization.ADO" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Docker.Core" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Messaging.FHIR" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Messaging.GS1" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Messaging.HL7" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.i18n" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Queue.Msmq" Condition="'$(TargetFramework)'=='net48'" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Messaging.Metadata" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Queue.RabbitMq" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.AppService" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.OAuth" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.WWW" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.DevTools" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Configuration" Version="$(VersionNumber)" Condition="'$(TargetFramework)'=='net48'" />
				<PackageReference Include="SanteDB.Core.Security.Tfa.Twilio" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Messaging.Atna" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Persistence.Diagnostics.Email" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Persistence.Diagnostics.Jira" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\restsrvr\RestSrvr\RestSrvr.csproj" />
				<ProjectReference Include="..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\santedb-applets\SanteDB.Core.Applets\SanteDB.Core.Applets.csproj" />
				<ProjectReference Include="..\santedb-bis\SanteDB.BI\SanteDB.BI.csproj" />
				<ProjectReference Include="..\santedb-bis\SanteDB.Rest.BIS\SanteDB.Rest.BIS.csproj" />
				<ProjectReference Include="..\santedb-bre-js\SanteDB.BusinessRules.JavaScript\SanteDB.BusinessRules.JavaScript.csproj" />
				<ProjectReference Include="..\santedb-cdss\SanteDB.Cdss.Xml\SanteDB.Cdss.Xml.csproj" />
				<ProjectReference Include="..\santedb-match\SanteDB.Matcher\SanteDB.Matcher.csproj" />
				<ProjectReference Include="..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
				<ProjectReference Include="..\santedb-orm\SanteDB.OrmLite\SanteDB.OrmLite.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Core.Model.AMI\SanteDB.Core.Model.AMI.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.AMI\SanteDB.Rest.AMI.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.Common\SanteDB.Rest.Common.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.HDSI\SanteDB.Rest.HDSI.csproj" />
				<ProjectReference Include="..\santedb-mdm\SanteDB.Persistence.MDM\SanteDB.Persistence.MDM.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Core.Model.ViewModelSerializers\SanteDB.Core.Model.ViewModelSerializers.csproj" />
				<ProjectReference Include="..\santedb-data\SanteDB.Persistence.Data\SanteDB.Persistence.Data.csproj" />

				<ProjectReference Include="..\santedb-cache-memory\SanteDB.Caching.Memory\SanteDB.Caching.Memory.csproj" />
				<ProjectReference Include="..\santedb-cache-redis\SanteDB.Caching.Redis\SanteDB.Caching.Redis.csproj" />
				<ProjectReference Include="..\santedb-certs-bc\SanteDB.Security.Certs.BouncyCastle\SanteDB.Security.Certs.BouncyCastle.csproj" />
				<ProjectReference Include="..\santedb-data\SanteDB.Persistence.Auditing.ADO\SanteDB.Persistence.Auditing.ADO.csproj" />
				<ProjectReference Include="..\santedb-data\SanteDB.Persistence.PubSub.ADO\SanteDB.Persistence.PubSub.ADO.csproj" />
				<ProjectReference Include="..\santedb-data\SanteDB.Persistence.Synchronization.ADO\SanteDB.Persistence.Synchronization.ADO.csproj" />
				<ProjectReference Include="..\santedb-docker\SanteDB.Docker.Core\SanteDB.Docker.Core.csproj" />
				<ProjectReference Include="..\santedb-fhir\SanteDB.Messaging.FHIR\SanteDB.Messaging.FHIR.csproj" />
				<ProjectReference Include="..\santedb-gs1\SanteDB.Messaging.GS1\SanteDB.Messaging.GS1.csproj" />
				<ProjectReference Include="..\santedb-hl7\SanteDB.Messaging.HL7\SanteDB.Messaging.HL7.csproj" />
				<ProjectReference Include="..\santedb-i18n\SanteDB.Core.i18n\SanteDB.Core.i18n.csproj" />
				<ProjectReference Include="..\santedb-msmq\SanteDB.Queue.Msmq\SanteDB.Queue.Msmq.csproj" Condition="'$(TargetFramework)'=='net48'" />
				<ProjectReference Include="..\santedb-openapi\SanteDB.Messaging.OpenAPI\SanteDB.Messaging.Metadata.csproj" />
				<ProjectReference Include="..\santedb-rabbitmq\SanteDB.Queue.RabbitMq\SanteDB.Queue.RabbitMq.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.AppService\SanteDB.Rest.AppService.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.OAuth\SanteDB.Rest.OAuth.csproj" />
				<ProjectReference Include="..\santedb-restsvc\SanteDB.Rest.WWW\SanteDB.Rest.WWW.csproj" />
				<ProjectReference Include="..\santedb-tools\SanteDB.DevTools\SanteDB.DevTools.csproj" />
				<ProjectReference Include="..\SanteDB.Configuration\SanteDB.Configuration.csproj" Condition="'$(TargetFramework)'=='net48'" />
				<ProjectReference Include="..\SanteDB.Core.Security.Tfa.Twilio\SanteDB.Core.Security.Tfa.Twilio.csproj" />
				<ProjectReference Include="..\SanteDB.Messaging.Atna\SanteDB.Messaging.Atna.csproj" />
				<ProjectReference Include="..\SanteDB.Persistence.Diagnostics.Email\SanteDB.Persistence.Diagnostics.Email.csproj" />
				<ProjectReference Include="..\SanteDB.Persistence.Diagnostics.Jira\SanteDB.Persistence.Diagnostics.Jira.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>
	<ItemGroup>
		<PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="9.1.1" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="[9.0.0,10)" />
		<PackageReference Include="Mono.Posix" Version="7.1.0-final.1.21458.1" />
		<PackageReference Include="SharpCompress" Version="0.50.4" />
		<PackageReference Include="System.Text.Json" Version="[9.0.0,10)" />
		<PackageReference Include="Newtonsoft.Json" Version="[13.0.4,13.1)" />
		<PackageReference Include="Npgsql" Version="[8.0.6,9)" />
		<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.10" />
		<PackageReference Include="SQLiteSpellfix.lib.e_sqlite3mc" Version="2.2.1" />
		<PackageReference Include="System.ServiceProcess.ServiceController" Version="[10.0.3,11)" />
		<PackageReference Include="System.Memory" Version="[4.6.3,5)" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="MohawkCollege.Util.Console.Parameters">
			<HintPath>..\Solution Items\MohawkCollege.Util.Console.Parameters.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Include="applets\*.pak">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<None Include="config\*.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="config\*.skel">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<None Include="Data\*.dataset">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="License.rtf">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<Content Include="icon.ico" />
	</ItemGroup>
</Project>